<?php
require_once __DIR__ . '/config.php';

header('Content-Type: application/json');

$villasToUpdate = [
    [
        'id' => 'villa-mahina',
        'name' => 'Villa Mahina – Luxury 3BR 400m Walk to Berawa Beach & Finns',
        'area' => 'Canggu & Berawa',
        'location' => 'Berawa, Canggu',
        'address' => 'Berawa, Canggu, Badung, Bali',
        'category' => 'Luxe',
        'tier' => 'Luxury',
        'price' => 380.00,
        'beds' => 3,
        'baths' => 3,
        'bathrooms' => 3,
        'guests' => 6,
        'rating' => 4.95,
        'reviews_count' => 12,
        'short_desc' => 'Villa kontemporer 3 kamar mewah di jantung Berawa, hanya 400 meter dari Pantai Berawa dan Finns Beach Club. Dilengkapi kolam renang pribadi, sunken lounge, dan jendela kedap suara total.',
        'description' => 'Villa kontemporer 3 kamar mewah di jantung Berawa, hanya 400 meter dari Pantai Berawa dan Finns Beach Club.',
        'full_desc' => 'Escape to Villa Mahina, in one of Canggu’s most sought-after locations. Just 400m from Berawa Beach and minutes from Finns Beach Club, this stylish 3-bedroom villa sits in a private residence, offering peace and privacy while being close to Canggu’s best restaurants, cafés, and nightlife.',
        'img' => '/airbnb/villa-mahina/photos/photo-01.jpg',
        'images' => json_encode(array_map(fn($i) => sprintf('/airbnb/villa-mahina/photos/photo-%02d.jpg', $i), range(1, 15))),
        'am' => json_encode(['Private pool', 'Sunken lounge', 'Walk to beach (400m)', 'Double-glazed soundproof windows', 'Air conditioning', 'High-speed WiFi', 'Full kitchen', 'Daily housekeeping']),
        'pick' => 1
    ],
    [
        'id' => 'khaleela-villas',
        'name' => 'Khaleela Villas – Desert-Inspired 2BR Oasis in Canggu',
        'area' => 'Canggu & Berawa',
        'location' => 'Canggu',
        'address' => 'Canggu, Badung, Bali',
        'category' => 'Standard',
        'tier' => 'Deluxe',
        'price' => 195.00,
        'beds' => 2,
        'baths' => 2,
        'bathrooms' => 2,
        'guests' => 4,
        'rating' => 4.88,
        'reviews_count' => 88,
        'short_desc' => 'Oase eksotis bertema gurun di pusat Canggu yang semarak. Menghadirkan 2 kamar tidur nyaman, kolam renang pribadi, kamar mandi terbuka tropis, dan dapur lengkap.',
        'description' => 'Oase eksotis bertema gurun di pusat Canggu yang semarak.',
        'full_desc' => 'Discover Khaleela Villas, a desert-inspired oasis in vibrant Canggu. Its unique charm captivates with immersive desert vibes. This single-story haven boasts two cozy bedrooms for a serene retreat. Lounge by the refreshing pool, basked in sunlight.',
        'img' => '/airbnb/khaleela-villas/photos/photo-01.jpg',
        'images' => json_encode(array_map(fn($i) => sprintf('/airbnb/khaleela-villas/photos/photo-%02d.jpg', $i), range(1, 15))),
        'am' => json_encode(['Private pool', 'Desert-inspired architecture', 'Outdoor tropical shower', 'Full kitchen', 'Air conditioning', 'High-speed WiFi', 'Daily housekeeping', 'Dedicated team']),
        'pick' => 1
    ],
    [
        'id' => 'beyond-the-palms',
        'name' => 'Beyond the Palms – High-Tech 4BR Luxury Villa with Rooftop',
        'area' => 'Canggu & Berawa',
        'location' => 'Canggu',
        'address' => 'Canggu, Badung, Bali',
        'category' => 'Luxe',
        'tier' => 'Luxury',
        'price' => 720.00,
        'beds' => 4,
        'baths' => 4,
        'bathrooms' => 4,
        'guests' => 8,
        'rating' => 4.88,
        'reviews_count' => 68,
        'short_desc' => 'Villa berteknologi tinggi 4 kamar baru di Canggu dengan kolam renang 45m², rooftop jacuzzi, sound system Sonos, TV 4K 86 inci, dan area barbekyu pribadi.',
        'description' => 'Villa berteknologi tinggi 4 kamar baru di Canggu dengan kolam renang 45m², rooftop jacuzzi, dan smart tech.',
        'full_desc' => 'Welcome to Beyond the Palms! This luxurious, high-tech 4-bedroom villa is perfect for anyone who wants a truly unforgettable Bali experience. Features 45sqm pool, massive garden, rooftop jacuzzi, Sonos sound system, and SMEG kitchen.',
        'img' => '/airbnb/beyond-the-palms/photos/photo-01.jpg',
        'images' => json_encode(array_map(fn($i) => sprintf('/airbnb/beyond-the-palms/photos/photo-%02d.jpg', $i), range(1, 15))),
        'am' => json_encode(['Private pool (45m²)', 'Rooftop jacuzzi', 'Yoga deck', 'Sonos sound system', '86" 4K Smart TV', 'SMEG kitchen', 'Outdoor cinema projector', 'Private BBQ grill']),
        'pick' => 1
    ],
    [
        'id' => 'villa-akar',
        'name' => 'Villa Akar – Elegant 4BR Contemporary Hideaway in Berawa',
        'area' => 'Canggu & Berawa',
        'location' => 'Berawa, Canggu',
        'address' => 'Berawa, Canggu, Badung, Bali',
        'category' => 'Luxe',
        'tier' => 'Luxury',
        'price' => 490.00,
        'beds' => 4,
        'baths' => 4.5,
        'bathrooms' => 5,
        'guests' => 8,
        'rating' => 5.00,
        'reviews_count' => 17,
        'short_desc' => 'Villa 4 kamar tidur elegan kontemporer berpredikat Guest Favorite (5.0 bintang) di jantung Berawa. Memiliki ruang keluarga fleksibel ber-AC, kolam renang asri, dan staf berdedikasi.',
        'description' => 'Villa 4 kamar tidur elegan kontemporer berpredikat Guest Favorite (5.0 bintang) di jantung Berawa.',
        'full_desc' => 'Discover Villa Akar, a contemporary four-bedroom villa set in one of Berawa’s most desirable pockets. Features unbeatable location near the beach, modern living spaces filled with natural light, and a dedicated hospitality team.',
        'img' => '/airbnb/villa-akar/photos/photo-01.jpg',
        'images' => json_encode(array_map(fn($i) => sprintf('/airbnb/villa-akar/photos/photo-%02d.jpg', $i), range(1, 15))),
        'am' => json_encode(['Private pool', 'Guest Favorite 5.0 rating', 'Flexible enclosed/open living', 'Designer architecture by Teduh', 'En-suite master suites', 'High-speed WiFi', 'Daily housekeeping']),
        'pick' => 1
    ],
    [
        'id' => 'villa-golden',
        'name' => 'Villa Golden – Modern Chic 2BR Villa Opposite FINNS Club',
        'area' => 'Canggu & Berawa',
        'location' => 'Berawa, Canggu',
        'address' => 'Berawa, Canggu, Badung, Bali',
        'category' => 'Deluxe',
        'tier' => 'Premium',
        'price' => 230.00,
        'beds' => 2,
        'baths' => 2,
        'bathrooms' => 2,
        'guests' => 4,
        'rating' => 4.89,
        'reviews_count' => 65,
        'short_desc' => 'Villa 2 kamar bergaya modern chic tepat di seberang Finns Recreation Club di Berawa. Dilengkapi kolam renang pribadi, interior mewah, dan staf pelayanan harian.',
        'description' => 'Villa 2 kamar bergaya modern chic tepat di seberang Finns Recreation Club di Berawa.',
        'full_desc' => 'Nestled in the vibrant Berawa neighborhood, Villa Golden offers a luxurious retreat for discerning travelers. Beautiful design and architecture, located directly opposite FINNS recreation club, few meters from top cafes.',
        'img' => '/airbnb/villa-golden/photos/photo-01.jpg',
        'images' => json_encode(array_map(fn($i) => sprintf('/airbnb/villa-golden/photos/photo-%02d.jpg', $i), range(1, 15))),
        'am' => json_encode(['Private pool', 'Opposite FINNS Recreation Club', 'Modern chic interior', 'Both en-suite bedrooms', 'Fully equipped kitchen', 'Air conditioning', 'Daily housekeeping']),
        'pick' => 1
    ],
    [
        'id' => 'villa-surga',
        'name' => 'Villa Surga – Serene 4BR Sanctuary with Private Pool in Ubud',
        'area' => 'Ubud',
        'location' => 'Ubud, Gianyar',
        'address' => 'Ubud, Gianyar, Bali',
        'category' => 'Retreat',
        'tier' => 'Premium',
        'price' => 320.00,
        'beds' => 4,
        'baths' => 4,
        'bathrooms' => 4,
        'guests' => 8,
        'rating' => 4.71,
        'reviews_count' => 87,
        'short_desc' => 'Sanctuary tropis privat 4 kamar di kawasan asri Ubud. Menyuguhkan kolam renang infinity pribadi, suasana hijau yang tenang, staf lengkap, dan akses mudah ke jantung budaya Ubud.',
        'description' => 'Sanctuary tropis privat 4 kamar di kawasan asri Ubud.',
        'full_desc' => 'Welcome to Villa Surga, a private 4-bedroom villa tucked into the lush surroundings of Ubud — ideal for families and groups seeking space, comfort, and a peaceful tropical setting close to Bali’s cultural heart.',
        'img' => '/airbnb/villa-surga/photos/photo-01.jpg',
        'images' => json_encode(array_map(fn($i) => sprintf('/airbnb/villa-surga/photos/photo-%02d.jpg', $i), range(1, 15))),
        'am' => json_encode(['Private infinity pool', 'Traditional Balinese entrance', 'Lush tropical valley view', 'Full villa staffing', 'All en-suite bathrooms', 'Spacious open living', 'Daily housekeeping']),
        'pick' => 1
    ]
];

$sql = "INSERT INTO villas (id, name, area, location, address, category, tier, price, beds, baths, bathrooms, guests, rating, reviews_count, short_desc, description, full_desc, img, images, am, pick)
VALUES (:id, :name, :area, :location, :address, :category, :tier, :price, :beds, :baths, :bathrooms, :guests, :rating, :reviews_count, :short_desc, :description, :full_desc, :img, :images, :am, :pick)
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    area = VALUES(area),
    location = VALUES(location),
    address = VALUES(address),
    category = VALUES(category),
    tier = VALUES(tier),
    price = VALUES(price),
    beds = VALUES(beds),
    baths = VALUES(baths),
    bathrooms = VALUES(bathrooms),
    guests = VALUES(guests),
    rating = VALUES(rating),
    reviews_count = VALUES(reviews_count),
    short_desc = VALUES(short_desc),
    description = VALUES(description),
    full_desc = VALUES(full_desc),
    img = VALUES(img),
    images = VALUES(images),
    am = VALUES(am),
    pick = VALUES(pick)";

$stmt = $pdo->prepare($sql);
$updatedCount = 0;

foreach ($villasToUpdate as $v) {
    $stmt->execute([
        ':id' => $v['id'],
        ':name' => $v['name'],
        ':area' => $v['area'],
        ':location' => $v['location'],
        ':address' => $v['address'],
        ':category' => $v['category'],
        ':tier' => $v['tier'],
        ':price' => $v['price'],
        ':beds' => $v['beds'],
        ':baths' => $v['baths'],
        ':bathrooms' => $v['bathrooms'],
        ':guests' => $v['guests'],
        ':rating' => $v['rating'],
        ':reviews_count' => $v['reviews_count'],
        ':short_desc' => $v['short_desc'],
        ':description' => $v['description'],
        ':full_desc' => $v['full_desc'],
        ':img' => $v['img'],
        ':images' => $v['images'],
        ':am' => $v['am'],
        ':pick' => $v['pick']
    ]);
    $updatedCount++;
}

echo json_encode([
    'success' => true,
    'message' => "Berhasil menyinkronkan {$updatedCount} villa ke database MySQL",
    'updatedCount' => $updatedCount
]);
